
export type ConfigType = {
  BACKEND_API_ENDPOINT: string;
  COGNITO_IDENTITY_POOL_ID: string;
  AWS_REGION: string;
  COGNITO_USER_POOL_ID: string;
  COGNITO_USER_POOL_WEB_CLIENT_ID: string;
  COGNITO_DOMAIN: string;
  COGNITO_REDIRECT_SIGNIN_WEB: string;
  COGNITO_REDIRECT_SIGNOUT_WEB: string;
  // CLIENT_AWS_ACCESS_KEY_ID: string;
  // CLIENT_AWS_ACCESS_SECRECT_KEY: string;
  // CLIENT_COGNITO_USER_POOL_ID: string;
  GIT_COMMIT: string;
  APP_BRANCH: string;
  HANDSHAKE_API_KEY: string;
  ONESIGNAL_APP_ID: string;
  AMPLITUDE_API_KEY: string;
};

const Config: ConfigType = {
  BACKEND_API_ENDPOINT: process.env.REACT_APP_BACKEND_API_ENDPOINT || '',
  COGNITO_IDENTITY_POOL_ID: '',
  AWS_REGION: '',
  COGNITO_USER_POOL_ID: '',
  COGNITO_USER_POOL_WEB_CLIENT_ID: '',
  COGNITO_DOMAIN: '',
  COGNITO_REDIRECT_SIGNIN_WEB: '',
  COGNITO_REDIRECT_SIGNOUT_WEB: '',
  // CLIENT_AWS_ACCESS_KEY_ID: '',
  // CLIENT_AWS_ACCESS_SECRECT_KEY: '',
  // CLIENT_COGNITO_USER_POOL_ID: '',
  GIT_COMMIT: process.env.REACT_APP_GIT_COMMIT || 'unknown',
  APP_BRANCH: process.env.REACT_APP_APP_BRANCH || 'unknown',
  HANDSHAKE_API_KEY: process.env.REACT_APP_HANDSHAKE_API_KEY || '',
  ONESIGNAL_APP_ID: process.env.REACT_APP_ONESIGNAL_APP_ID || '',
  AMPLITUDE_API_KEY: process.env.REACT_APP_AMPLITUDE_API_KEY || '',
};

export default Config;